#!/data/data/com.termux/files/usr/bin/bash -e
clear
echo -e "\e[33m\e[1m apt is updating"
apt-get update -y
clear
apt-get upgrade -y
clear
echo -e "\e[35m\e[1m


RRRRRRRRRRRRRRRRR                                   YYYYYYY       YYYYYYY
R::::::::::::::::R                                  Y:::::Y       Y:::::Y
R::::::RRRRRR:::::R                                 Y:::::Y       Y:::::Y
RR:::::R     R:::::R                                Y::::::Y     Y::::::Y
  R::::R     R:::::R aaaaaaaaaaaaa  zzzzzzzzzzzzzzzzYYY:::::Y   Y:::::YYY
  R::::R     R:::::R a::::::::::::a z:::::::::::::::z  Y:::::Y Y:::::Y
  R::::RRRRRR:::::R  aaaaaaaaa:::::az::::::::::::::z    Y:::::Y:::::Y
  R:::::::::::::RR            a::::azzzzzzzz::::::z      Y:::::::::Y
  R::::RRRRRR:::::R    aaaaaaa:::::a      z::::::z        Y:::::::Y
  R::::R     R:::::R aa::::::::::::a     z::::::z          Y:::::Y
  R::::R     R:::::Ra::::aaaa::::::a    z::::::z           Y:::::Y
  R::::R     R:::::a::::a    a:::::a   z::::::z            Y:::::Y
RR:::::R     R:::::a::::a    a:::::a  z::::::zzzzzzzz      Y:::::Y
R::::::R     R:::::a:::::aaaa::::::a z::::::::::::::z   YYYY:::::YYYY
R::::::R     R:::::Ra::::::::::aa:::z:::::::::::::::z   Y:::::::::::Y
RRRRRRRR     RRRRRRR aaaaaaaaaa  aaazzzzzzzzzzzzzzzzz   YYYYYYYYYYYYY


"

echo -e "\e[34m\e[1m [1] Enter For Full"
echo -e "\e[34m\e[1m [2] Enter For Lite"
echo -e "\e[34m\e[1m [3] Enter For Nano
